---
- name: Killing process using target ports Run 1
  shell: |
    fuser -k 6443/tcp
    fuser -k 8080/tcp
    fuser -k 8081/tcp
    fuser -k 8383/tcp
    fuser -k 9254/tcp
    fuser -k 9256/tcp
    fuser -k 10250/tcp
    fuser -k 10255/tcp
    fuser -k 10257/tcp
    fuser -k 10259/tcp
  with_sequence: count=3
  ignore_errors: True